/**
 * Writes lib/wrapper-errors.ts from the AUTHORITATIVE wrapper error table
 * (~/percolator-ops/ledger/error-codes-<sha>.md, compiler-checked by the gate agent), and
 * refuses to write unless it agrees EXACTLY with the oracle fixture's `allErrors` (rustc
 * ordinals from our own oracle build, __tests__/fixtures/limits/rust-p3-final.json).
 *   npx tsx scripts/limits-parity/p3-final/gen-wrapper-errors.ts <error-codes.md>
 * __tests__/lib/wrapper-errors-parity.test.ts pins the file to the fixture.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const root = join(__dirname, "..", "..", "..");
const tablePath = process.argv[2];
if (!tablePath) throw new Error("usage: gen-wrapper-errors.ts <error-codes-<sha>.md>");
const fx = JSON.parse(readFileSync(join(root, "__tests__/fixtures/limits/rust-p3-final.json"), "utf8")) as {
  p3Sha: string;
  /** Wrapper commit `allErrors` was taken at, when newer than the rest of the oracle (p3Sha). */
  allErrorsSha?: string;
  allErrors: Record<string, number>;
};

// "| 21 | 0x15 | `EngineLockActive` | `LockActive` | 985 | … |"
const table: Record<string, number> = {};
for (const line of readFileSync(tablePath, "utf8").split("\n")) {
  const m = /^\|\s*(\d+)\s*\|\s*0x([0-9a-f]+)\s*\|\s*`([A-Za-z0-9]+)`\s*\|/.exec(line);
  if (!m) continue;
  const n = Number(m[1]);
  if (parseInt(m[2], 16) !== n) throw new Error(`table row ${m[3]}: hex 0x${m[2]} != ${n}`);
  if (table[m[3]] !== undefined) throw new Error(`table: duplicate ${m[3]}`);
  table[m[3]] = n;
}
const names = new Set([...Object.keys(table), ...Object.keys(fx.allErrors)]);
const diff = [...names].filter((n) => table[n] !== fx.allErrors[n]);
if (Object.keys(table).length === 0) throw new Error("no rows parsed from the table");
if (diff.length) throw new Error(`table and oracle disagree: ${diff.map((n) => `${n} table=${table[n]} oracle=${fx.allErrors[n]}`).join("; ")}`);

const rows = Object.entries(table).sort((a, b) => a[1] - b[1]);
rows.forEach(([, v], i) => {
  if (v !== i) throw new Error(`gap/duplicate at ${i}`);
});
writeFileSync(
  join(root, "lib/wrapper-errors.ts"),
  `/**
 * GENERATED by scripts/limits-parity/p3-final/gen-wrapper-errors.ts from the authoritative
 * table ${basename(tablePath)} (cross-checked equal to the oracle fixture's rustc ordinals,
 * wrapper ${(fx.allErrorsSha ?? fx.p3Sha).slice(0, 8)}). Every wrapper PercolatorError ordinal the app maps comes from
 * here; do not edit by hand. A Custom(n) means THIS table only when the wrapper program itself
 * raised it (decode by the failing program id; CPI callees reuse the same numbers).
 */
export const WRAPPER_ERR = {
${rows.map(([n, v]) => `  ${n}: ${v},`).join("\n")}
} as const;

export type WrapperErrorName = keyof typeof WRAPPER_ERR;
`,
);
console.log(`wrote ${rows.length} wrapper error codes (table == oracle)`);
